sudo: required

services:
  - docker

language: java

before_script:
  - echo "Starting build"

script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notification:
  email: false

after_script:
  - echo "Script finished"
  - echo "Test result. $TRAVIS_TEST_RESULT"


after_success:
  - sh ./deploy_dockerhub.sh
  - sh ./deploy_heroku.sh

after_failure:
  - echo "Build was failed"